// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appointment_reminder_events_mark_failed.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const markAppointmentReminderEventFailed = `-- name: MarkAppointmentReminderEventFailed :exec
UPDATE appointment_reminder_events
SET last_attempt_at = NOW(),
    attempts = attempts + 1,
    last_error = $2
WHERE id = $1
  AND sent_at IS NULL
`

type MarkAppointmentReminderEventFailedParams struct {
	ID        uuid.UUID      `db:"id"`
	LastError sql.NullString `db:"last_error"`
}

// MarkAppointmentReminderEventFailed
//
//	UPDATE appointment_reminder_events
//	SET last_attempt_at = NOW(),
//	    attempts = attempts + 1,
//	    last_error = $2
//	WHERE id = $1
//	  AND sent_at IS NULL
func (q *Queries) MarkAppointmentReminderEventFailed(ctx context.Context, db DBTX, arg MarkAppointmentReminderEventFailedParams) error {
	_, err := db.ExecContext(ctx, markAppointmentReminderEventFailed, arg.ID, arg.LastError)
	return err
}
