// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appointments_mark_unattended_no_show.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const markUnattendedAppointmentsNoShow = `-- name: MarkUnattendedAppointmentsNoShow :many
UPDATE appointments
SET status = 'no_show',
    updated_at = NOW(),
    cancelled_by = NULL,
    cancel_reason = NULL,
    cancelled_at = NULL,
    completed_at = NULL
WHERE status = 'confirmed'
  AND starts_at <= NOW() - INTERVAL '30 minutes'
RETURNING id, tenant_id, customer_id
`

type MarkUnattendedAppointmentsNoShowRow struct {
	ID         uuid.UUID `db:"id"`
	TenantID   uuid.UUID `db:"tenant_id"`
	CustomerID uuid.UUID `db:"customer_id"`
}

// MarkUnattendedAppointmentsNoShow
//
//	UPDATE appointments
//	SET status = 'no_show',
//	    updated_at = NOW(),
//	    cancelled_by = NULL,
//	    cancel_reason = NULL,
//	    cancelled_at = NULL,
//	    completed_at = NULL
//	WHERE status = 'confirmed'
//	  AND starts_at <= NOW() - INTERVAL '30 minutes'
//	RETURNING id, tenant_id, customer_id
func (q *Queries) MarkUnattendedAppointmentsNoShow(ctx context.Context, db DBTX) ([]MarkUnattendedAppointmentsNoShowRow, error) {
	rows, err := db.QueryContext(ctx, markUnattendedAppointmentsNoShow)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarkUnattendedAppointmentsNoShowRow
	for rows.Next() {
		var i MarkUnattendedAppointmentsNoShowRow
		if err := rows.Scan(&i.ID, &i.TenantID, &i.CustomerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
