// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appointment_reminder_events_find_pending.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findPendingAppointmentReminderEvents = `-- name: FindPendingAppointmentReminderEvents :many
SELECT e.id,
       e.appointment_id,
       e.tenant_id,
       e.customer_id,
       e.reminder_type,
       e.attempts,
       a.starts_at
FROM appointment_reminder_events e
         JOIN appointments a ON a.id = e.appointment_id
WHERE e.sent_at IS NULL
  AND e.attempts < 5
  AND a.status = 'confirmed'
ORDER BY e.created_at
LIMIT 500
`

type FindPendingAppointmentReminderEventsRow struct {
	ID            uuid.UUID `db:"id"`
	AppointmentID uuid.UUID `db:"appointment_id"`
	TenantID      uuid.UUID `db:"tenant_id"`
	CustomerID    uuid.UUID `db:"customer_id"`
	ReminderType  string    `db:"reminder_type"`
	Attempts      int32     `db:"attempts"`
	StartsAt      time.Time `db:"starts_at"`
}

// FindPendingAppointmentReminderEvents
//
//	SELECT e.id,
//	       e.appointment_id,
//	       e.tenant_id,
//	       e.customer_id,
//	       e.reminder_type,
//	       e.attempts,
//	       a.starts_at
//	FROM appointment_reminder_events e
//	         JOIN appointments a ON a.id = e.appointment_id
//	WHERE e.sent_at IS NULL
//	  AND e.attempts < 5
//	  AND a.status = 'confirmed'
//	ORDER BY e.created_at
//	LIMIT 500
func (q *Queries) FindPendingAppointmentReminderEvents(ctx context.Context, db DBTX) ([]FindPendingAppointmentReminderEventsRow, error) {
	rows, err := db.QueryContext(ctx, findPendingAppointmentReminderEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindPendingAppointmentReminderEventsRow
	for rows.Next() {
		var i FindPendingAppointmentReminderEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.AppointmentID,
			&i.TenantID,
			&i.CustomerID,
			&i.ReminderType,
			&i.Attempts,
			&i.StartsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
