// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appointment_penalty_events_insert.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertAppointmentPenaltyEvent = `-- name: InsertAppointmentPenaltyEvent :execrows
INSERT INTO appointment_penalty_events(
    id,
    appointment_id,
    tenant_id,
    customer_id,
    event_type,
    occurred_at,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    NOW()
)
ON CONFLICT (appointment_id, event_type) DO NOTHING
`

type InsertAppointmentPenaltyEventParams struct {
	ID            uuid.UUID `db:"id"`
	AppointmentID uuid.UUID `db:"appointment_id"`
	TenantID      uuid.UUID `db:"tenant_id"`
	CustomerID    uuid.UUID `db:"customer_id"`
	EventType     string    `db:"event_type"`
	OccurredAt    time.Time `db:"occurred_at"`
}

// InsertAppointmentPenaltyEvent
//
//	INSERT INTO appointment_penalty_events(
//	    id,
//	    appointment_id,
//	    tenant_id,
//	    customer_id,
//	    event_type,
//	    occurred_at,
//	    created_at
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6,
//	    NOW()
//	)
//	ON CONFLICT (appointment_id, event_type) DO NOTHING
func (q *Queries) InsertAppointmentPenaltyEvent(ctx context.Context, db DBTX, arg InsertAppointmentPenaltyEventParams) (int64, error) {
	result, err := db.ExecContext(ctx, insertAppointmentPenaltyEvent,
		arg.ID,
		arg.AppointmentID,
		arg.TenantID,
		arg.CustomerID,
		arg.EventType,
		arg.OccurredAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
