// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appointments_mark_reminder_sent_by_type.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const markAppointmentReminderSentByType = `-- name: MarkAppointmentReminderSentByType :exec
UPDATE appointments
SET reminder_24h_sent_at = CASE
                               WHEN $1::text = '24h'
                                   THEN COALESCE(reminder_24h_sent_at, NOW())
                               ELSE reminder_24h_sent_at
    END,
    reminder_1h_sent_at  = CASE
                               WHEN $1::text = '1h'
                                   THEN COALESCE(reminder_1h_sent_at, NOW())
                               ELSE reminder_1h_sent_at
        END
WHERE id = $2::uuid
  AND status = 'confirmed'
`

type MarkAppointmentReminderSentByTypeParams struct {
	ReminderType  string    `db:"reminder_type"`
	AppointmentID uuid.UUID `db:"appointment_id"`
}

// MarkAppointmentReminderSentByType
//
//	UPDATE appointments
//	SET reminder_24h_sent_at = CASE
//	                               WHEN $1::text = '24h'
//	                                   THEN COALESCE(reminder_24h_sent_at, NOW())
//	                               ELSE reminder_24h_sent_at
//	    END,
//	    reminder_1h_sent_at  = CASE
//	                               WHEN $1::text = '1h'
//	                                   THEN COALESCE(reminder_1h_sent_at, NOW())
//	                               ELSE reminder_1h_sent_at
//	        END
//	WHERE id = $2::uuid
//	  AND status = 'confirmed'
func (q *Queries) MarkAppointmentReminderSentByType(ctx context.Context, db DBTX, arg MarkAppointmentReminderSentByTypeParams) error {
	_, err := db.ExecContext(ctx, markAppointmentReminderSentByType, arg.ReminderType, arg.AppointmentID)
	return err
}
