// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointment_reminder_events_mark_sent.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const markAppointmentReminderEventSent = `-- name: MarkAppointmentReminderEventSent :exec
UPDATE appointment_reminder_events
SET sent_at = NOW(),
    last_attempt_at = NOW(),
    attempts = attempts + 1,
    last_error = NULL
WHERE id = $1
  AND sent_at IS NULL
`

// MarkAppointmentReminderEventSent
//
//	UPDATE appointment_reminder_events
//	SET sent_at = NOW(),
//	    last_attempt_at = NOW(),
//	    attempts = attempts + 1,
//	    last_error = NULL
//	WHERE id = $1
//	  AND sent_at IS NULL
func (q *Queries) MarkAppointmentReminderEventSent(ctx context.Context, db DBTX, id uuid.UUID) error {
	_, err := db.ExecContext(ctx, markAppointmentReminderEventSent, id)
	return err
}
