// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers_find_by_phone_number.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const findCustomerByPhoneNumber = `-- name: FindCustomerByPhoneNumber :one
SELECT id, tenant_id, phone_number, name, is_blocked, created_at
FROM customers
WHERE tenant_id = $1
  AND phone_number = $2
LIMIT 1
`

type FindCustomerByPhoneNumberParams struct {
	TenantID    uuid.UUID `db:"tenant_id"`
	PhoneNumber string    `db:"phone_number"`
}

type FindCustomerByPhoneNumberRow struct {
	ID          uuid.UUID      `db:"id"`
	TenantID    uuid.UUID      `db:"tenant_id"`
	PhoneNumber string         `db:"phone_number"`
	Name        sql.NullString `db:"name"`
	IsBlocked   bool           `db:"is_blocked"`
	CreatedAt   time.Time      `db:"created_at"`
}

// FindCustomerByPhoneNumber
//
//	SELECT id, tenant_id, phone_number, name, is_blocked, created_at
//	FROM customers
//	WHERE tenant_id = $1
//	  AND phone_number = $2
//	LIMIT 1
func (q *Queries) FindCustomerByPhoneNumber(ctx context.Context, db DBTX, arg FindCustomerByPhoneNumberParams) (FindCustomerByPhoneNumberRow, error) {
	row := db.QueryRowContext(ctx, findCustomerByPhoneNumber, arg.TenantID, arg.PhoneNumber)
	var i FindCustomerByPhoneNumberRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PhoneNumber,
		&i.Name,
		&i.IsBlocked,
		&i.CreatedAt,
	)
	return i, err
}
