// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers_increment_no_shows_batch.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const incrementCustomersNoShowsBatch = `-- name: IncrementCustomersNoShowsBatch :exec
WITH args AS (
    SELECT
        $1::uuid[] AS customer_ids,
        $2::uuid[] AS tenant_ids,
        $3::int[] AS increments
),
updates AS (
    SELECT
        UNNEST(args.customer_ids) AS customer_id,
        UNNEST(args.tenant_ids) AS tenant_id,
        UNNEST(args.increments) AS increment_by
    FROM args
)
UPDATE customers AS c
SET no_show_count = c.no_show_count + updates.increment_by
FROM updates
WHERE c.id = updates.customer_id
  AND c.tenant_id = updates.tenant_id
`

type IncrementCustomersNoShowsBatchParams struct {
	CustomerIds []uuid.UUID `db:"customer_ids"`
	TenantIds   []uuid.UUID `db:"tenant_ids"`
	Increments  []int32     `db:"increments"`
}

// IncrementCustomersNoShowsBatch
//
//	WITH args AS (
//	    SELECT
//	        $1::uuid[] AS customer_ids,
//	        $2::uuid[] AS tenant_ids,
//	        $3::int[] AS increments
//	),
//	updates AS (
//	    SELECT
//	        UNNEST(args.customer_ids) AS customer_id,
//	        UNNEST(args.tenant_ids) AS tenant_id,
//	        UNNEST(args.increments) AS increment_by
//	    FROM args
//	)
//	UPDATE customers AS c
//	SET no_show_count = c.no_show_count + updates.increment_by
//	FROM updates
//	WHERE c.id = updates.customer_id
//	  AND c.tenant_id = updates.tenant_id
func (q *Queries) IncrementCustomersNoShowsBatch(ctx context.Context, db DBTX, arg IncrementCustomersNoShowsBatchParams) error {
	_, err := db.ExecContext(ctx, incrementCustomersNoShowsBatch, pq.Array(arg.CustomerIds), pq.Array(arg.TenantIds), pq.Array(arg.Increments))
	return err
}
