// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers_find_by_id.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const findCustomerByID = `-- name: FindCustomerByID :one
SELECT id,
       tenant_id,
       phone_number,
       name,
       is_blocked,
       no_show_count,
       late_cancel_count,
       created_at
FROM customers
WHERE id = $1
LIMIT 1
`

type FindCustomerByIDRow struct {
	ID              uuid.UUID      `db:"id"`
	TenantID        uuid.UUID      `db:"tenant_id"`
	PhoneNumber     string         `db:"phone_number"`
	Name            sql.NullString `db:"name"`
	IsBlocked       bool           `db:"is_blocked"`
	NoShowCount     int32          `db:"no_show_count"`
	LateCancelCount int32          `db:"late_cancel_count"`
	CreatedAt       time.Time      `db:"created_at"`
}

// FindCustomerByID
//
//	SELECT id,
//	       tenant_id,
//	       phone_number,
//	       name,
//	       is_blocked,
//	       no_show_count,
//	       late_cancel_count,
//	       created_at
//	FROM customers
//	WHERE id = $1
//	LIMIT 1
func (q *Queries) FindCustomerByID(ctx context.Context, db DBTX, id uuid.UUID) (FindCustomerByIDRow, error) {
	row := db.QueryRowContext(ctx, findCustomerByID, id)
	var i FindCustomerByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PhoneNumber,
		&i.Name,
		&i.IsBlocked,
		&i.NoShowCount,
		&i.LateCancelCount,
		&i.CreatedAt,
	)
	return i, err
}
