// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers_penalty_counts.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const findCustomerPenaltyCounts = `-- name: FindCustomerPenaltyCounts :one
SELECT no_show_count,
       late_cancel_count
FROM customers
WHERE id = $1
  AND tenant_id = $2
`

type FindCustomerPenaltyCountsParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

type FindCustomerPenaltyCountsRow struct {
	NoShowCount     int32 `db:"no_show_count"`
	LateCancelCount int32 `db:"late_cancel_count"`
}

// FindCustomerPenaltyCounts
//
//	SELECT no_show_count,
//	       late_cancel_count
//	FROM customers
//	WHERE id = $1
//	  AND tenant_id = $2
func (q *Queries) FindCustomerPenaltyCounts(ctx context.Context, db DBTX, arg FindCustomerPenaltyCountsParams) (FindCustomerPenaltyCountsRow, error) {
	row := db.QueryRowContext(ctx, findCustomerPenaltyCounts, arg.ID, arg.TenantID)
	var i FindCustomerPenaltyCountsRow
	err := row.Scan(&i.NoShowCount, &i.LateCancelCount)
	return i, err
}
