// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: onboarding_progress_complete.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const completeOnboardingProgress = `-- name: CompleteOnboardingProgress :exec
UPDATE onboarding_progress
SET completed_at = NOW(),
    updated_at   = NOW()
WHERE tenant_id = $1
`

// CompleteOnboardingProgress
//
//	UPDATE onboarding_progress
//	SET completed_at = NOW(),
//	    updated_at   = NOW()
//	WHERE tenant_id = $1
func (q *Queries) CompleteOnboardingProgress(ctx context.Context, db DBTX, tenantID uuid.UUID) error {
	_, err := db.ExecContext(ctx, completeOnboardingProgress, tenantID)
	return err
}
