// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: onboarding_progress_insert.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertOnboardingProgress = `-- name: InsertOnboardingProgress :exec
INSERT INTO onboarding_progress (id, tenant_id, current_step)
VALUES ($1, $2, $3)
`

type InsertOnboardingProgressParams struct {
	ID          uuid.UUID `db:"id"`
	TenantID    uuid.UUID `db:"tenant_id"`
	CurrentStep int32     `db:"current_step"`
}

// InsertOnboardingProgress
//
//	INSERT INTO onboarding_progress (id, tenant_id, current_step)
//	VALUES ($1, $2, $3)
func (q *Queries) InsertOnboardingProgress(ctx context.Context, db DBTX, arg InsertOnboardingProgressParams) error {
	_, err := db.ExecContext(ctx, insertOnboardingProgress, arg.ID, arg.TenantID, arg.CurrentStep)
	return err
}
