// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: onboarding_progress_advance_step.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const advanceOnboardingStep = `-- name: AdvanceOnboardingStep :exec
UPDATE onboarding_progress
SET current_step = current_step + 1,
    updated_at   = NOW()
WHERE tenant_id = $1
  AND current_step < $2
`

type AdvanceOnboardingStepParams struct {
	TenantID    uuid.UUID `db:"tenant_id"`
	CurrentStep int32     `db:"current_step"`
}

// AdvanceOnboardingStep
//
//	UPDATE onboarding_progress
//	SET current_step = current_step + 1,
//	    updated_at   = NOW()
//	WHERE tenant_id = $1
//	  AND current_step < $2
func (q *Queries) AdvanceOnboardingStep(ctx context.Context, db DBTX, arg AdvanceOnboardingStepParams) error {
	_, err := db.ExecContext(ctx, advanceOnboardingStep, arg.TenantID, arg.CurrentStep)
	return err
}
