// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans_list_active.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const listActivePlans = `-- name: ListActivePlans :many
SELECT id,
       external_id,
       name,
       description,
       price,
       currency,
       "interval"
FROM plans
WHERE is_active = true
  AND environment = $1
`

type ListActivePlansRow struct {
	ID          uuid.UUID      `db:"id"`
	ExternalID  string         `db:"external_id"`
	Name        string         `db:"name"`
	Description sql.NullString `db:"description"`
	Price       int32          `db:"price"`
	Currency    string         `db:"currency"`
	Interval    sql.NullString `db:"interval"`
}

// ListActivePlans
//
//	SELECT id,
//	       external_id,
//	       name,
//	       description,
//	       price,
//	       currency,
//	       "interval"
//	FROM plans
//	WHERE is_active = true
//	  AND environment = $1
func (q *Queries) ListActivePlans(ctx context.Context, db DBTX, environment string) ([]ListActivePlansRow, error) {
	rows, err := db.QueryContext(ctx, listActivePlans, environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivePlansRow
	for rows.Next() {
		var i ListActivePlansRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Currency,
			&i.Interval,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
