// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resource_services_delete.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteResourceService = `-- name: DeleteResourceService :exec
DELETE
FROM resource_services
WHERE resource_id = $1
`

// DeleteResourceService
//
//	DELETE
//	FROM resource_services
//	WHERE resource_id = $1
func (q *Queries) DeleteResourceService(ctx context.Context, db DBTX, resourceID uuid.UUID) error {
	_, err := db.ExecContext(ctx, deleteResourceService, resourceID)
	return err
}
