// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources_delete.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteResource = `-- name: DeleteResource :exec
UPDATE resources
SET is_active = false
WHERE id = $1
  AND tenant_id = $2
`

type DeleteResourceParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

// DeleteResource
//
//	UPDATE resources
//	SET is_active = false
//	WHERE id = $1
//	  AND tenant_id = $2
func (q *Queries) DeleteResource(ctx context.Context, db DBTX, arg DeleteResourceParams) error {
	_, err := db.ExecContext(ctx, deleteResource, arg.ID, arg.TenantID)
	return err
}
