// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resources_insert.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const insertResource = `-- name: InsertResource :exec
INSERT INTO resources(
    id,
    tenant_id,
    name,
    type,
    avatar_url,
    is_active,
    sort_order
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    true,
    $6
)
`

type InsertResourceParams struct {
	ID        uuid.UUID      `db:"id"`
	TenantID  uuid.UUID      `db:"tenant_id"`
	Name      string         `db:"name"`
	Type      string         `db:"type"`
	AvatarUrl sql.NullString `db:"avatar_url"`
	SortOrder int32          `db:"sort_order"`
}

// InsertResource
//
//	INSERT INTO resources(
//	    id,
//	    tenant_id,
//	    name,
//	    type,
//	    avatar_url,
//	    is_active,
//	    sort_order
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    true,
//	    $6
//	)
func (q *Queries) InsertResource(ctx context.Context, db DBTX, arg InsertResourceParams) error {
	_, err := db.ExecContext(ctx, insertResource,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Type,
		arg.AvatarUrl,
		arg.SortOrder,
	)
	return err
}
