// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resource_services_insert.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertResourceService = `-- name: InsertResourceService :exec
INSERT INTO resource_services (resource_id, service_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertResourceServiceParams struct {
	ResourceID uuid.UUID `db:"resource_id"`
	ServiceID  uuid.UUID `db:"service_id"`
}

// InsertResourceService
//
//	INSERT INTO resource_services (resource_id, service_id)
//	VALUES ($1, $2)
//	ON CONFLICT DO NOTHING
func (q *Queries) InsertResourceService(ctx context.Context, db DBTX, arg InsertResourceServiceParams) error {
	_, err := db.ExecContext(ctx, insertResourceService, arg.ResourceID, arg.ServiceID)
	return err
}
