// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedule_overrides_delete.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteScheduleOverride = `-- name: DeleteScheduleOverride :exec
DELETE
FROM schedule_overrides
WHERE id = $1
  AND resource_id = $2
`

type DeleteScheduleOverrideParams struct {
	ID         uuid.UUID `db:"id"`
	ResourceID uuid.UUID `db:"resource_id"`
}

// DeleteScheduleOverride
//
//	DELETE
//	FROM schedule_overrides
//	WHERE id = $1
//	  AND resource_id = $2
func (q *Queries) DeleteScheduleOverride(ctx context.Context, db DBTX, arg DeleteScheduleOverrideParams) error {
	_, err := db.ExecContext(ctx, deleteScheduleOverride, arg.ID, arg.ResourceID)
	return err
}
