// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenant_users_link_tenant_user.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const linkTenantUser = `-- name: LinkTenantUser :exec
INSERT INTO tenant_users (user_id, tenant_id, role)
VALUES ($1, $2, 'admin')
ON CONFLICT (user_id, tenant_id) DO NOTHING
`

type LinkTenantUserParams struct {
	UserID   string    `db:"user_id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

// LinkTenantUser
//
//	INSERT INTO tenant_users (user_id, tenant_id, role)
//	VALUES ($1, $2, 'admin')
//	ON CONFLICT (user_id, tenant_id) DO NOTHING
func (q *Queries) LinkTenantUser(ctx context.Context, db DBTX, arg LinkTenantUserParams) error {
	_, err := db.ExecContext(ctx, linkTenantUser, arg.UserID, arg.TenantID)
	return err
}
