// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants_find_by_slug.sql

package db

import (
	"context"
)

const findTenantBySlug = `-- name: FindTenantBySlug :one
SELECT id,
       name,
       slug,
       timezone,
       currency,
       plan,
       plan_expires_at,
       appointments_this_month,
       month_reset_at,
       is_active,
       settings,
       created_at,
       updated_at
FROM tenants
WHERE slug = $1
  AND is_active = true
LIMIT 1
`

// FindTenantBySlug
//
//	SELECT id,
//	       name,
//	       slug,
//	       timezone,
//	       currency,
//	       plan,
//	       plan_expires_at,
//	       appointments_this_month,
//	       month_reset_at,
//	       is_active,
//	       settings,
//	       created_at,
//	       updated_at
//	FROM tenants
//	WHERE slug = $1
//	  AND is_active = true
//	LIMIT 1
func (q *Queries) FindTenantBySlug(ctx context.Context, db DBTX, slug string) (Tenant, error) {
	row := db.QueryRowContext(ctx, findTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Timezone,
		&i.Currency,
		&i.Plan,
		&i.PlanExpiresAt,
		&i.AppointmentsThisMonth,
		&i.MonthResetAt,
		&i.IsActive,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
