// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_whatsapp_configs_update.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const updateTenantWhatsappConfig = `-- name: UpdateTenantWhatsappConfig :exec
UPDATE tenant_whatsapp_configs
SET access_token     = $1,
    token_expires_at = $2,
    verified_at      = $3,
    updated_at       = NOW()
WHERE id = $4
`

type UpdateTenantWhatsappConfigParams struct {
	AccessToken    sql.NullString `db:"access_token"`
	TokenExpiresAt sql.NullTime   `db:"token_expires_at"`
	VerifiedAt     sql.NullTime   `db:"verified_at"`
	ID             uuid.UUID      `db:"id"`
}

// UpdateTenantWhatsappConfig
//
//	UPDATE tenant_whatsapp_configs
//	SET access_token     = $1,
//	    token_expires_at = $2,
//	    verified_at      = $3,
//	    updated_at       = NOW()
//	WHERE id = $4
func (q *Queries) UpdateTenantWhatsappConfig(ctx context.Context, db DBTX, arg UpdateTenantWhatsappConfigParams) error {
	_, err := db.ExecContext(ctx, updateTenantWhatsappConfig,
		arg.AccessToken,
		arg.TokenExpiresAt,
		arg.VerifiedAt,
		arg.ID,
	)
	return err
}
