// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants_update_appointment_count.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const updateTenantAppointmentCount = `-- name: UpdateTenantAppointmentCount :exec
UPDATE tenants
SET appointments_this_month = $2,
    updated_at              = NOW()
WHERE id = $1
`

type UpdateTenantAppointmentCountParams struct {
	ID                    uuid.UUID `db:"id"`
	AppointmentsThisMonth int32     `db:"appointments_this_month"`
}

// UpdateTenantAppointmentCount
//
//	UPDATE tenants
//	SET appointments_this_month = $2,
//	    updated_at              = NOW()
//	WHERE id = $1
func (q *Queries) UpdateTenantAppointmentCount(ctx context.Context, db DBTX, arg UpdateTenantAppointmentCountParams) error {
	_, err := db.ExecContext(ctx, updateTenantAppointmentCount, arg.ID, arg.AppointmentsThisMonth)
	return err
}
