// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenant_whatsapp_configs_find_pending_activations.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const findTenantPendingActivations = `-- name: FindTenantPendingActivations :many
SELECT wc.tenant_id,
       t.name                                    AS tenant_name,
       COALESCE(wc.activation_contact_email, '') AS contact_email,
       wc.activation_status,
       wc.activation_requested_at,
       COALESCE(wc.activation_notes, '')         AS activation_notes
FROM tenant_whatsapp_configs wc
         JOIN tenants t ON t.id = wc.tenant_id
WHERE wc.activation_status = 'pending'
ORDER BY wc.activation_requested_at
`

type FindTenantPendingActivationsRow struct {
	TenantID              uuid.UUID                `db:"tenant_id"`
	TenantName            string                   `db:"tenant_name"`
	ContactEmail          string                   `db:"contact_email"`
	ActivationStatus      WhatsappActivationStatus `db:"activation_status"`
	ActivationRequestedAt sql.NullTime             `db:"activation_requested_at"`
	ActivationNotes       string                   `db:"activation_notes"`
}

// FindTenantPendingActivations
//
//	SELECT wc.tenant_id,
//	       t.name                                    AS tenant_name,
//	       COALESCE(wc.activation_contact_email, '') AS contact_email,
//	       wc.activation_status,
//	       wc.activation_requested_at,
//	       COALESCE(wc.activation_notes, '')         AS activation_notes
//	FROM tenant_whatsapp_configs wc
//	         JOIN tenants t ON t.id = wc.tenant_id
//	WHERE wc.activation_status = 'pending'
//	ORDER BY wc.activation_requested_at
func (q *Queries) FindTenantPendingActivations(ctx context.Context, db DBTX) ([]FindTenantPendingActivationsRow, error) {
	rows, err := db.QueryContext(ctx, findTenantPendingActivations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindTenantPendingActivationsRow
	for rows.Next() {
		var i FindTenantPendingActivationsRow
		if err := rows.Scan(
			&i.TenantID,
			&i.TenantName,
			&i.ContactEmail,
			&i.ActivationStatus,
			&i.ActivationRequestedAt,
			&i.ActivationNotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
