// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_whatsapp_configs_insert.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const insertTenantWhatsappConfig = `-- name: InsertTenantWhatsappConfig :exec
INSERT INTO tenant_whatsapp_configs(
    id,
    tenant_id,
    activation_status,
    activation_requested_at,
    activation_contact_email,
    activation_notes
) VALUES ($1, $2, 'pending', NOW(), $3, $4)
ON CONFLICT (tenant_id) DO UPDATE
    SET activation_status        = 'pending',
        activation_requested_at  = NOW(),
        activation_contact_email = EXCLUDED.activation_contact_email,
        activation_notes         = EXCLUDED.activation_notes
`

type InsertTenantWhatsappConfigParams struct {
	ID                     uuid.UUID      `db:"id"`
	TenantID               uuid.UUID      `db:"tenant_id"`
	ActivationContactEmail sql.NullString `db:"activation_contact_email"`
	ActivationNotes        sql.NullString `db:"activation_notes"`
}

// InsertTenantWhatsappConfig
//
//	INSERT INTO tenant_whatsapp_configs(
//	    id,
//	    tenant_id,
//	    activation_status,
//	    activation_requested_at,
//	    activation_contact_email,
//	    activation_notes
//	) VALUES ($1, $2, 'pending', NOW(), $3, $4)
//	ON CONFLICT (tenant_id) DO UPDATE
//	    SET activation_status        = 'pending',
//	        activation_requested_at  = NOW(),
//	        activation_contact_email = EXCLUDED.activation_contact_email,
//	        activation_notes         = EXCLUDED.activation_notes
func (q *Queries) InsertTenantWhatsappConfig(ctx context.Context, db DBTX, arg InsertTenantWhatsappConfigParams) error {
	_, err := db.ExecContext(ctx, insertTenantWhatsappConfig,
		arg.ID,
		arg.TenantID,
		arg.ActivationContactEmail,
		arg.ActivationNotes,
	)
	return err
}
