// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_whatsapp_configs_activate.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const activateTenantWhatsappConfig = `-- name: ActivateTenantWhatsappConfig :exec
UPDATE tenant_whatsapp_configs
SET waba_id              = $1,
    phone_number_id      = $2,
    display_phone_number = $3,
    access_token         = $4,
    activation_status    = 'active',
    is_active            = true,
    verified_at          = NOW()
WHERE tenant_id = $5
`

type ActivateTenantWhatsappConfigParams struct {
	WabaID             sql.NullString `db:"waba_id"`
	PhoneNumberID      sql.NullString `db:"phone_number_id"`
	DisplayPhoneNumber sql.NullString `db:"display_phone_number"`
	AccessToken        sql.NullString `db:"access_token"`
	TenantID           uuid.UUID      `db:"tenant_id"`
}

// ActivateTenantWhatsappConfig
//
//	UPDATE tenant_whatsapp_configs
//	SET waba_id              = $1,
//	    phone_number_id      = $2,
//	    display_phone_number = $3,
//	    access_token         = $4,
//	    activation_status    = 'active',
//	    is_active            = true,
//	    verified_at          = NOW()
//	WHERE tenant_id = $5
func (q *Queries) ActivateTenantWhatsappConfig(ctx context.Context, db DBTX, arg ActivateTenantWhatsappConfigParams) error {
	_, err := db.ExecContext(ctx, activateTenantWhatsappConfig,
		arg.WabaID,
		arg.PhoneNumberID,
		arg.DisplayPhoneNumber,
		arg.AccessToken,
		arg.TenantID,
	)
	return err
}
