// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants_find_by_user_id.sql

package db

import (
	"context"
)

const findTenantByUserId = `-- name: FindTenantByUserId :one
SELECT t.id,
       t.name,
       t.slug,
       t.timezone,
       t.currency,
       t.appointments_this_month,
       t.month_reset_at,
       t.is_active,
       t.settings,
       t.created_at,
       t.updated_at
FROM tenants t
         JOIN tenant_users tu ON tu.tenant_id = t.id
WHERE tu.user_id = $1
  AND t.is_active = true
LIMIT 1
`

// FindTenantByUserId
//
//	SELECT t.id,
//	       t.name,
//	       t.slug,
//	       t.timezone,
//	       t.currency,
//	       t.appointments_this_month,
//	       t.month_reset_at,
//	       t.is_active,
//	       t.settings,
//	       t.created_at,
//	       t.updated_at
//	FROM tenants t
//	         JOIN tenant_users tu ON tu.tenant_id = t.id
//	WHERE tu.user_id = $1
//	  AND t.is_active = true
//	LIMIT 1
func (q *Queries) FindTenantByUserId(ctx context.Context, db DBTX, userID string) (Tenant, error) {
	row := db.QueryRowContext(ctx, findTenantByUserId, userID)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Timezone,
		&i.Currency,
		&i.AppointmentsThisMonth,
		&i.MonthResetAt,
		&i.IsActive,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
