// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: working_hours_find_by_resource.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const findResourceWorkingHours = `-- name: FindResourceWorkingHours :many
SELECT id,
       resource_id,
       day_of_week,
       start_time::text,
       end_time::text,
       is_active
FROM working_hours
WHERE resource_id = $1
ORDER BY day_of_week
`

type FindResourceWorkingHoursRow struct {
	ID         uuid.UUID `db:"id"`
	ResourceID uuid.UUID `db:"resource_id"`
	DayOfWeek  int16     `db:"day_of_week"`
	StartTime  string    `db:"start_time"`
	EndTime    string    `db:"end_time"`
	IsActive   bool      `db:"is_active"`
}

// FindResourceWorkingHours
//
//	SELECT id,
//	       resource_id,
//	       day_of_week,
//	       start_time::text,
//	       end_time::text,
//	       is_active
//	FROM working_hours
//	WHERE resource_id = $1
//	ORDER BY day_of_week
func (q *Queries) FindResourceWorkingHours(ctx context.Context, db DBTX, resourceID uuid.UUID) ([]FindResourceWorkingHoursRow, error) {
	rows, err := db.QueryContext(ctx, findResourceWorkingHours, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindResourceWorkingHoursRow
	for rows.Next() {
		var i FindResourceWorkingHoursRow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
