// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: working_hours_upsert.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const upsertWorkingHours = `-- name: UpsertWorkingHours :exec
INSERT INTO working_hours(
    id,
    resource_id,
    day_of_week,
    start_time,
    end_time,
    is_active
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
) ON CONFLICT (resource_id, day_of_week) DO UPDATE
    SET start_time = EXCLUDED.start_time,
        end_time   = EXCLUDED.end_time,
        is_active  = EXCLUDED.is_active
`

type UpsertWorkingHoursParams struct {
	ID         uuid.UUID `db:"id"`
	ResourceID uuid.UUID `db:"resource_id"`
	DayOfWeek  int16     `db:"day_of_week"`
	StartTime  time.Time `db:"start_time"`
	EndTime    time.Time `db:"end_time"`
	IsActive   bool      `db:"is_active"`
}

// UpsertWorkingHours
//
//	INSERT INTO working_hours(
//	    id,
//	    resource_id,
//	    day_of_week,
//	    start_time,
//	    end_time,
//	    is_active
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6
//	) ON CONFLICT (resource_id, day_of_week) DO UPDATE
//	    SET start_time = EXCLUDED.start_time,
//	        end_time   = EXCLUDED.end_time,
//	        is_active  = EXCLUDED.is_active
func (q *Queries) UpsertWorkingHours(ctx context.Context, db DBTX, arg UpsertWorkingHoursParams) error {
	_, err := db.ExecContext(ctx, upsertWorkingHours,
		arg.ID,
		arg.ResourceID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.IsActive,
	)
	return err
}
