// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: working_hours_delete.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteWorkingHour = `-- name: DeleteWorkingHour :exec
DELETE
FROM working_hours
WHERE id = $1
  AND resource_id = $2
`

type DeleteWorkingHourParams struct {
	ID         uuid.UUID `db:"id"`
	ResourceID uuid.UUID `db:"resource_id"`
}

// DeleteWorkingHour
//
//	DELETE
//	FROM working_hours
//	WHERE id = $1
//	  AND resource_id = $2
func (q *Queries) DeleteWorkingHour(ctx context.Context, db DBTX, arg DeleteWorkingHourParams) error {
	_, err := db.ExecContext(ctx, deleteWorkingHour, arg.ID, arg.ResourceID)
	return err
}
